//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_emp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_emp()
        {
            this.inf_clte = new HashSet<inf_clte>();
            this.inf_fisc = new HashSet<inf_fisc>();
            this.inf_inv = new HashSet<inf_inv>();
            this.inf_prov = new HashSet<inf_prov>();
            this.inf_usr = new HashSet<inf_usr>();
        }
    
        public System.Guid empID { get; set; }
        public Nullable<int> est_empID { get; set; }
        public string nom { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string calle_num { get; set; }
        public string d_codigo { get; set; }
        public int id_asenta_cpcons { get; set; }
        public Nullable<System.DateTime> fech_reg { get; set; }
    
        public virtual fact_est_emp fact_est_emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_clte> inf_clte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_fisc> inf_fisc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_inv> inf_inv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_prov> inf_prov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_usr> inf_usr { get; set; }
    }
}
