//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_fisc
    {
        public System.Guid fiscID { get; set; }
        public Nullable<int> est_fiscID { get; set; }
        public string cod_fisc { get; set; }
        public Nullable<int> tipo_rfcID { get; set; }
        public string rfc { get; set; }
        public string rs { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string callenum { get; set; }
        public string d_codigo { get; set; }
        public Nullable<int> id_asenta_cpcons { get; set; }
        public string coment { get; set; }
        public Nullable<System.DateTime> fech_reg { get; set; }
        public System.Guid empID { get; set; }
        public System.Guid usrID { get; set; }
    
        public virtual fact_est_fisc fact_est_fisc { get; set; }
        public virtual fact_tipo_rfc fact_tipo_rfc { get; set; }
        public virtual inf_emp inf_emp { get; set; }
    }
}
