//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_usr
    {
        public System.Guid usrID { get; set; }
        public Nullable<int> est_usrID { get; set; }
        public Nullable<int> tipo_usrID { get; set; }
        public string code_usr { get; set; }
        public string noms { get; set; }
        public string apat { get; set; }
        public string amat { get; set; }
        public string usr { get; set; }
        public string clave { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string calle_num { get; set; }
        public string d_codigo { get; set; }
        public Nullable<int> id_asenta_cpcons { get; set; }
        public Nullable<System.DateTime> fech_reg { get; set; }
        public System.Guid empID { get; set; }
    
        public virtual fact_est_usr fact_est_usr { get; set; }
        public virtual fact_tipo_usr fact_tipo_usr { get; set; }
        public virtual inf_emp inf_emp { get; set; }
    }
}
