//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_inv
    {
        public System.Guid inv_prodID { get; set; }
        public Nullable<int> est_inv_prodID { get; set; }
        public System.Guid catID { get; set; }
        public System.Guid marcaID { get; set; }
        public System.Guid lineaID { get; set; }
        public string cod_inv_prod { get; set; }
        public string desc_inv_prod { get; set; }
        public string code { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> cant_min { get; set; }
        public Nullable<decimal> cost_compra { get; set; }
        public Nullable<int> margen { get; set; }
        public System.Guid empID { get; set; }
        public Nullable<System.Guid> usrID { get; set; }
        public Nullable<System.DateTime> fech_reg { get; set; }
    
        public virtual fact_cat fact_cat { get; set; }
        public virtual fact_est_inv_prod fact_est_inv_prod { get; set; }
        public virtual fact_linea fact_linea { get; set; }
        public virtual fact_marca fact_marca { get; set; }
        public virtual inf_emp inf_emp { get; set; }
    }
}
