//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_admEntities : DbContext
    {
        public db_admEntities()
            : base("name=db_admEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fact_cat> fact_cat { get; set; }
        public virtual DbSet<fact_est_clte> fact_est_clte { get; set; }
        public virtual DbSet<fact_est_emp> fact_est_emp { get; set; }
        public virtual DbSet<fact_est_fisc> fact_est_fisc { get; set; }
        public virtual DbSet<fact_est_inv_prod> fact_est_inv_prod { get; set; }
        public virtual DbSet<fact_est_prov> fact_est_prov { get; set; }
        public virtual DbSet<fact_est_usr> fact_est_usr { get; set; }
        public virtual DbSet<fact_linea> fact_linea { get; set; }
        public virtual DbSet<fact_marca> fact_marca { get; set; }
        public virtual DbSet<fact_tipo_rfc> fact_tipo_rfc { get; set; }
        public virtual DbSet<fact_tipo_usr> fact_tipo_usr { get; set; }
        public virtual DbSet<inf_clte> inf_clte { get; set; }
        public virtual DbSet<inf_emp> inf_emp { get; set; }
        public virtual DbSet<inf_fisc> inf_fisc { get; set; }
        public virtual DbSet<inf_inv> inf_inv { get; set; }
        public virtual DbSet<inf_prov> inf_prov { get; set; }
        public virtual DbSet<inf_sepomex> inf_sepomex { get; set; }
        public virtual DbSet<inf_usr> inf_usr { get; set; }
    }
}
